Numpy Numerical python -- Which is much much fater than Loops
Methematical Operation
Statical operations

Loops are slow and Numpy is fast

Numpy arrays: C-Speed

Vectorised --> Rows and columns

In [3]:
import numpy as np
import time

n = 10_000_000

#Python List
python_list = list(range(n))
start = time.time()
result = [x * 2 for x in python_list]
python_time = time.time() - start

np_array = np.arange(n)
start = time.time()
result= np_array * 2
numpy_time = time.time() - start

print(f"Python list:  {python_time:.4f}s")
print(f"NumPy array:  {numpy_time:.4f}s")
print(f"NumPy is {python_time/numpy_time:.0f}x FASTER!")


Python list:  0.6917s
NumPy array:  0.1506s
NumPy is 5x FASTER!


In [31]:
#Creating Arrays

import numpy as np
import random

a = np.array([1, 2, 3, 4, 5])
print(f"From list to array {a}")

range_arr = np.arange(0, 10) #--> Start is 0 end is n-1 10 - 1= 9  Step is 2
print(range_arr)
# print( np.arange(0, 10, 2))

random_arr = np.random.randint(1, 100, size=5) #5 random numbers between 1 and 100
print(random_arr)

zeros = np.zeros((3, 3)) # rows * colomns
print(zeros)


ones = np.ones((2, 3))
print(ones)


From list to array [1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[82 31 20 68 93]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix )
print(matrix.shape)
print(matrix.size)

print(matrix.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64


In [23]:
#indexing and Slicing

a = np.array([10, 20, 30, 40, 50])

# print(a)
# print(a[0])
# print(a[-1])
# print(f"a[1:4]: {a[1:4]}")
# print(a[::2])
print(a[::-1])

[50 40 30 20 10]


In [ ]:
#2D Indexing

m = np.array([[1, 2, 3],
            [4, 5, 6], 
              [7, 8, 9]])

# print(m)

# print(m[0,0]) #rows,  Columns

# print(m[1, :]) #Entire Row 1
# print(m[:, 0]) #Entire Column 0
# print(m[0:2, 1:])
# print(m[0:2, 0:2])
# print(m[1:3, 1:3])
# print(m[0:2, :])


# print(m[1:, 1:])

# print(m[:, ::-1])

# print(m[1:, 0:2])



# 1. m[1:, 1:]
# 2. m[:2, :2]
# 3. m[2, :]
# 4. m[:, 2]
# 5. m[::-1]
# 6. m[:, ::-1]
# 7. m[::2, ::2]
# 8. m[1, 0:2]
# 9. m[0:3:2, :]
# 10. m[1:, :2]


In [50]:
#Filtering

scores = np.array([45, 78, 92, 55, 88, 34, 76])

# print(scores)

# print(f"Scores above 60: {scores[scores > 60]}")

#print scores above 60 and below 85--> scores between 60 to 85

# print(f"Scores between 60 and 85 : {scores[(scores > 60) & (scores < 85)]}")

high_idex = np.where(scores> 80)
print(high_idex)

(array([2, 4]),)


In [61]:
#Arithmetic Operations

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# print(a)
# print(b)

# print(a+b)
# print(a-b)
# print(b-a)

# print(a ** 2)
print(a/2)

print(np.sqrt(a))




[0.5 1.  1.5 2. ]
[1.         1.41421356 1.73205081 2.        ]


In [71]:
data = np.array([4,2,7,3,6,9,8,1])

print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.max(data))
print(np.min(data))

#Standard Deviation
print(f"{np.std(data):.2f}")

40
5.0
5.0
9
1
2.74


In [75]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.sum(matrix))
print(np.sum(matrix, axis=0)) #== Column
print(np.sum(matrix, axis=1))

print(np.mean(matrix, axis=1))

45
[12 15 18]
[ 6 15 24]
[2. 5. 8.]


In [76]:
#Real World ML Application
#Data Nomailisation

# 1. Normalization (data preprocessing)
print("=== NORMALIZATION ===")
data = np.array([100, 200, 150, 300])

mean = np.mean(data)
std = np.std(data)
normalized = (data - mean) / std

print(f"Original: {data}")
print(f"Normalized: {normalized}")
print(f"New mean: {np.mean(normalized):.6f}, std: {np.std(normalized):.6f}")

=== NORMALIZATION ===
Original: [100 200 150 300]
Normalized: [-1.18321596  0.16903085 -0.50709255  1.52127766]
New mean: 0.000000, std: 1.000000


In [ ]:
#Cosine Similarity Module
print("=== COSINE SIMILARITY ===")

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

embed1 = np.array([1.0, 0.0, 0.0])
embed2 = np.array([1.0, 0.0, 0.0])  # identical
embed3 = np.array([0.0, 1.0, 0.0])  # orthogonal

print(f"Identical vectors: {cosine_similarity(embed1, embed2):.4f}")
print(f"Orthogonal vectors: {cosine_similarity(embed1, embed3):.4f}")



=== COSINE SIMILARITY ===
Identical vectors: 1.0000
Orthogonal vectors: 0.0000


In [78]:
# Batch Processing 

# 3. Batch Processing (neural networks)
print("=== BATCH PROCESSING ===")

# Batch of 4 samples, 5 features each
X = np.array([[1, 2, 3, 4, 5],
              [2, 3, 4, 5, 6],
              [3, 4, 5, 6, 7],
              [4, 5, 6, 7, 8]])

# Weight matrix: 5 inputs -> 3 outputs
W = np.random.randn(5, 3)

# Forward pass: compute all 4 samples at once
output = X @ W

print(f"Input shape: {X.shape} (4 samples, 5 features)")
print(f"Weight shape: {W.shape} (5 inputs, 3 outputs)")
print(f"Output shape: {output.shape} (4 samples, 3 outputs)")
print(f"\nFirst sample output: {output[0]}")


=== BATCH PROCESSING ===
Input shape: (4, 5) (4 samples, 5 features)
Weight shape: (5, 3) (5 inputs, 3 outputs)
Output shape: (4, 3) (4 samples, 3 outputs)

First sample output: [ 3.49321906  2.86747042 -3.25781187]


In [79]:
# 4. Loss Computation
print("=== LOSS COMPUTATION ===")

# Mean Squared Error
y_true = np.array([1.0, 2.0, 3.0])
y_pred = np.array([1.1, 2.2, 2.9])

mse = np.mean((y_true - y_pred) ** 2)
print(f"MSE Loss: {mse:.6f}")

# Accuracy
y_true_labels = np.array([0, 1, 1, 0])
y_pred_labels = np.array([0, 1, 0, 0])

accuracy = np.mean(y_true_labels == y_pred_labels)
print(f"Accuracy: {accuracy:.2%}")

=== LOSS COMPUTATION ===
MSE Loss: 0.020000
Accuracy: 75.00%


np.array --> Basic Array
zeros and ones -> np.zeros(3,3)
range --> np.arange(0, 10, 2)
Indexing --> arr[0] or arr[1]
Slicing --> arr[1:4]
Filtering --> arr[arr > 5] 
Math functions --> 
Stats functions --> 

ML and AI. ---> Calculation

Numpy is faster for Operations
Vectors and parallel processing
Essential for ML/AI work
Focus on Filterin Slicing and Indexing

Cursor IDE -- AI Programs

Antigravity -- Agents

Agent mode --> Cntrl + shift + N -- Windows users
Mac user --> cmd+shift+N 


UV Package Manager 

Chat Completions Model alli --> Our first AI Program